security:


    providers:
        our_db_provider:
                entity:
                  class: App\Entity\User
#                property: username
#        db_email:
#            entity:
#                class: App\Entity\User
#                property: email


#        all_users:
#            chain:
#                providers: ['db_username', 'db_email']

#    chain_provider:
#        chain:
#            providers: [db_username, db_email]
#                db_email:
            #            entity:
            #                class: App\Entity\User
            #                property: email

    #        in_memory:
#            memory:
#                users:
#                    foo: { password: test }
#        user_db:
#            entity: { class: AppBundle\Entity\User, property: username }
#
#


    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: user_home
                failure_path: fail
                csrf_parameter: _csrf_security_token
                csrf_token_id: a_private_string
            logout_on_user_change: true
            logout:
                path: logout
                target: /
                # where to redirect after logout
                # target: app_any_route



    encoders:
        App\Entity\User:
            algorithm: bcrypt

    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/monProfil', roles: IS_AUTHENTICATED_FULLY }

#    remember_me:
#        secret:   '%kernel.secret%'
#        lifetime: 2592000 # 30 jours, c'est optionnel, par defaut c'est 1 an

