security:


    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: user_home
                failure_path: fail
                csrf_parameter: _csrf_security_token
                csrf_token_id: a_private_string
            logout_on_user_change: true
            logout:
                path: logout
                target: /
                # where to redirect after logout
                # target: app_any_route



    encoders:
        App\Entity\User:
            algorithm: bcrypt

    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/monProfil', roles: IS_AUTHENTICATED_FULLY }


